### ISSUE TITLE
morpheus-graphql-cli uses hidden packages

### ISSUE THREAD

**Issue by coderfromhere** [morpheusgraphql/morpheus-graphql-cli#6]
```
resolver: lts-16.13
allow-newer: true
extra-deps:
  - git: https://github.com/morpheusgraphql/morpheus-graphql
    commit: 9d4e6347463b28484d8fee167ec05f5aec5a6164
    subdirs:
      - .
      - morpheus-graphql-core
      - morpheus-graphql-client
  - git: https://github.com/morpheusgraphql/morpheus-graphql-cli
    commit: 4b3bfbd0b8f5de1b43023e21be7b0eb5d2790b5c
```

Produces:
```
$ stack build morpheus-graphql-cli
Stack has not been tested with GHC versions above 8.6, and using 8.8.4, this may fail
Stack has not been tested with Cabal versions above 2.4, but version 3.0.1.0 was found, this may fail
WARNING: Ignoring morpheus-graphql-cli's bounds on optparse-applicative (>=0.12 && <0.15); using optparse-applicative-0.15.1.0.
Reason: allow-newer enabled.
morpheus-graphql-cli> configure
morpheus-graphql-cli> Configuring morpheus-graphql-cli-0.1.0...
morpheus-graphql-cli> build
morpheus-graphql-cli> Preprocessing executable 'morpheus' for morpheus-graphql-cli-0.1.0..
morpheus-graphql-cli> Building executable 'morpheus' for morpheus-graphql-cli-0.1.0..
morpheus-graphql-cli> [1 of 7] Compiling Paths_morpheus_graphql_cli
morpheus-graphql-cli> [2 of 7] Compiling Rendering.Terms
morpheus-graphql-cli> 
morpheus-graphql-cli> /private/var/folders/f8/z6c2znxs6xq0ylyhmxqvnjgh0000gp/T/stack-ac1054b8c689166d/morpheus-graphql-cli-0.1.0/src/Rendering/Terms.hs:29:1: error:
morpheus-graphql-cli>     Could not load module ‘Data.Morpheus.Types.Internal.AST’
morpheus-graphql-cli>     It is a member of the hidden package ‘morpheus-graphql-core-0.14.1’.
morpheus-graphql-cli>     Perhaps you need to add ‘morpheus-graphql-core’ to the build-depends in your .cabal file.
morpheus-graphql-cli>     Use -v (or `:set -v` in ghci) to see a list of the files searched for.
morpheus-graphql-cli>    |
morpheus-graphql-cli> 29 | import           Data.Morpheus.Types.Internal.AST
morpheus-graphql-cli>    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
morpheus-graphql-cli> 
```
